### ISSUE TITLE
How to send file pdf 

### ISSUE THREAD

**Issue by flexsoluciones** [wppconnect-team/wppconnect-server#908]
how send file pdf files 

"sendMsgResult": "ERROR_UNKNOWN"

**Comment by Saifallak** [comment]
@flexsoluciones please add re-produce steps and at least the request you sent and received

**Comment by icleitoncosta** [comment]
I will close the Issue due to lack of feedback.

But first I will leave an easy format for testing that can help other people.

Start the server.
Access: IP:PORT/api-docs
Generate the token for the session
Use the route ":SESSION/send-file-base64"
It already has a practical example of how to send in PDF format.
